### ISSUE TITLE
Hasiru Dala: User creation and access for Superset Utthaan dashboard.

### ISSUE THREAD

**Issue by kameshbhariya** [OpenCHS/hasiru-dala#109]
- [x] Create users for Utthaan dashboard and provide them with required access.
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/11atSZIdib6AG3bwXJLON06KwJc9IyMCXlbWJnljJBLw/edit?gid=0#gid=0)

Users to be created for the following:

- [x] HUL
- [x] UNDP
- [x] HD
- [x] Avani
- [x] DBRC
- [x] CFSD
- [x] CFED
- [x] SMS
- [x] Vikas Udanshive (Person)
- [x] Chintan

**Comment by adamsanadi6** [comment]
@kameshbhariya ,User creation for HUL and UNDP has been completed.

<img width="1540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU03Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f08a68fb92693069ed9e051ea54c6c27b5c1435b/Screenshot%202024-08-07%20at%203.28.11%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 3.28.11 PM.png" />

**Comment by adamsanadi6** [comment]
Putting this card on hold since there is a blocker on one of the charts in Detailed dashboard.

[Card link](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/hasiru-dala/113)

**Comment by kameshbhariya** [comment]
Tested the card, all the users are created in superset.
