### ISSUE TITLE
Hasiru Dala: Issue with dashboard filter.

### ISSUE THREAD

**Issue by kameshbhariya** [OpenCHS/hasiru-dala#110]
[Utthaan Summary Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/90/) and [Utthaan Detailed Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/88/?native_filters_key=qOScU6kc5j-Oj5Y0KycaTsBcMuuKHxn3Vbhhxpz91XhHh9VEHzuoBrd05I1IP068) have issue with filter.

Steps to reproduce:
1. Select **State** as Karnataka in filter.

Actual Result: The count and list of cities is displayed as only 2.

Expected Result: Count and list of cities should display all 19 cities.

**Comment by adamsanadi6** [comment]
@kameshbhariya @pkundu , After debugging, I discovered that this is not a bug but a mistake made while uploading the locations to production. City locations were uploaded without mapping them to the respective states.

```
SET ROLE utthaan ;

SELECT
	DISTINCT o."name",
	a."State",
	a."City"
FROM
	utthaan.address a
JOIN organisation o ON
	a.organisation_id = o.id
WHERE
	a."State" IS NULL
	AND a."City" IS NOT NULL
ORDER BY
	1, 2, 3
```
