### ISSUE TITLE
Hasiru Dala: Check categorisation of schemes in app.

### ISSUE THREAD

**Issue by kameshbhariya** [OpenCHS/hasiru-dala#111]

**Comment by adamsanadi6** [comment]
@kameshbhariya After discussing with Sachin, here’s the solution:

Step 1: Add a “Category” question immediately after the “Schemes” question. This question should be visible only if a general scheme is specified.
Step 2: When a general scheme is defined, automatically populate the “Category” question with the corresponding value.
