### ISSUE TITLE
Hasiru Dala: Review and add HD Reports descriptions.

### ISSUE THREAD

**Issue by kameshbhariya** [OpenCHS/hasiru-dala#112]
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1AOU3bsbdc_hfZGRdUc50mgEkd4ZMQ8aa/edit?gid=1905290076#gid=1905290076&range=30:49)

- [x] [Description](https://docs.google.com/document/d/1kccu9-0w2O8Ne-N9zdRxmUcN5WiaO4Vg/edit)

**Comment by Dinesh2019** [comment]
In the requirment 1. The total number of registered individuals, who are waste pickers is displayed in this tile.
But in the detailed dashboard 1. The total number of registered individuals, who are waste pickers is displayed in the 'Number of Individual Registered' tile.
and in summary dashboard 1. The total number of registered individuals, who are waste pickers is displayed in this tile.
can we have the same format across all the report
