### ISSUE TITLE
[HD Social Security] UAT Feedback

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/hasiru-dala#86]
Org name - Hasiru_KA_UAT

Form changes:

- [x] Avail Service encounter - Make "Select schemes to be availed" Single Select.
- [x] Under Hasiru Dala Training program, Add a field "Date of training program" - Data type as Date. 
- [x] Allow past date to be selected in Date of training program.
- [x] User should not be allowed to enter a date before enrollment and date of future in Date of training program.
- [x] Add field to capture image of KYC under KYC details section.

**Comment by Gojo-Taqi** [comment]
ETC :- 15 mins
Completed in :- 9 mins
