### ISSUE TITLE
[[Hasiru Dala SS] Changes in logic to populate schemes

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/hasiru-dala#87]
**Context**
In the Social security program, for Avail services encounter, the KYC schemes, General security schemes and Training programs questions show coded options based on the identity documents available with beneficiary. The availability of specific documents is captured in Registration form.

**Goal**
The coded values shown in the question has some changes in conditions. Update the rule to show the coded values accordingly.
Avail Services encounter - form requirements:
https://docs.google.com/spreadsheets/d/1L8fs4PJdvxk9aG4y4Z6dM_khxVx3x7DqlZ0KHeeLntI/edit#gid=0
Original logic:
https://docs.google.com/spreadsheets/d/1L8fs4PJdvxk9aG4y4Z6dM_khxVx3x7DqlZ0KHeeLntI/edit#gid=1926191430
Updated logic:
https://docs.google.com/spreadsheets/d/1L8fs4PJdvxk9aG4y4Z6dM_khxVx3x7DqlZ0KHeeLntI/edit#gid=1774136221

- [x] Make changes in the logic condition as given in this sheet for following questions - look at the changes highlighted in yellow legend.
1. Select the KYC service to be availed
2. Select schemes to be availed
3. Select the training program
https://docs.google.com/spreadsheets/d/1L8fs4PJdvxk9aG4y4Z6dM_khxVx3x7DqlZ0KHeeLntI/edit#gid=1774136221

**Comment by salilsamanvay** [comment]
@utkarshavni to add suggestions made by @sachsk

**Comment by salilsamanvay** [comment]
Moved this to ready lane as a back up card, if someone pickup this card then has to put up an estimate on this card before starting work on it. otherwise we will estimate it on 29th Aug estimation call

**Comment by vedfordev** [comment]
## Developer's Note :

#### Presupposition :
As we see in rule, in most of case if requirement is **above 18** then we earlier considered **ageInYears > 17**.

#### Logic :
1. for **KYC to populate** and **General SS Schemes to populate** checked existing rule and made changes according to that
2. for **Hasiru Dala Training Program** took reference from above two rule  and added condition

**Comment by vedfordev** [comment]
@sachsk @utkarshavni 

If we check in rule **above 18** we added in rule **ageInYear > 17**. but if you check **General SS Schemes to populate** for rule **Free Exam Training for SC/ST and Backward** requirement is **above 15** and earlier added as **ageInyear > 15**. So please check once.

**Comment by Dinesh2019** [comment]
1. Scholorship for Higher Education for girls (PUC) for this age is above 21 years need to calculated by the scheme display for 21 years age itself 
2. Scholorsip for High School Girls also as the same scenario.
3. We have to look for all the above scenarios 
4. RTE - less tha 5 years and 10 months but in the scheme we can able to see the RTE

**Comment by Dinesh2019** [comment]
@salilsamanvay @utkarshavni we have the Translation to Kannada for Hasiru Dala Training Program but we are missing do we need to work on the translation (missing in both UAT and Prod )

As discussed separatae card is created for transalation
