### ISSUE TITLE
[HD Support] Upload share locations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/hasiru-dala#88]
Support ticket - https://avni.freshdesk.com/a/tickets/2797

Production Organisation - **Hasiru Dala KA**

- [ ] Upload Urban Hierarchy as given in the csv
- [ ] Upload Rural Hierarchy as given in the csv

**Comment by utkarshavni** [comment]
Closing the issue as the locations have been uploaded and ticket resolved.
