### ISSUE TITLE
Move changes to production

### ISSUE THREAD

**Issue by salilsamanvay** [OpenCHS/hasiru-dala#90]
Move changes from UAT to Production:

UAT org: Hasiru KA UAT
Production org: Hasiru dala Karnataka

**Comment by salilsamanvay** [comment]
Check the org names once

**Comment by Gojo-Taqi** [comment]
Got 2 errors after uploading the Hasiru UAT bundle to prod.
1. Address level types are different
2. Some concepts are getting used twice in household registration form.

**Comment by Gojo-Taqi** [comment]
Got 2 errors after uploading the Hasiru UAT bundle to prod.
1. Address level types are different
2. Some concepts are getting used twice in household registration form.

**Comment by Gojo-Taqi** [comment]
On running the below script, you should be able to see that there is a concept getting used in a single form more than once.
`select * from form_element fe where form_element_group_id in (4938,
4939,
4940,
6208,
6207)
and concept_id = 114183
;`

But the strange part is that one of them is voided.
Will need to look into this issue deeper and find out whether it's a product bug or not.

**Comment by salilsamanvay** [comment]
@nupoorkhandelwal can you please review this card so that we can close the epic, we have deployed the changes to production, and need to send the final communication to the client..

**Comment by salilsamanvay** [comment]
@sachsk @Gojo-Taqi this is high priority as client is not able to work on the app
